package studio.aroudhub.ticketing.docker;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class DockerSchemaSqlTest {

    @Test
    // Docker 초기 스키마에 refresh token 식별자와 사용자 외래 키를 정의한다.
    void refreshTokenTable_referencesUsers() throws IOException {
        String schemaSql = Files.readString(Path.of("docker", "db", "init", "01-schema.sql"));

        assertThat(schemaSql)
                .contains("CREATE TABLE IF NOT EXISTS refresh_token")
                .contains("refresh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
                .contains("user_id INTEGER NOT NULL")
                .contains("FOREIGN KEY (user_id) REFERENCES users (users_id)")
                .contains("token VARCHAR(255) NOT NULL")
                .contains("expired_at TIMESTAMP NOT NULL");
    }
}
