CREATE TABLE IF NOT EXISTS users (
    users_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS venue (
    venue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS concert (
    concert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id INTEGER NOT NULL,
    img_url VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    booking_cnt INTEGER NOT NULL,
    status VARCHAR(255),
    created_at DATE NOT NULL,
    running_time INTEGER,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    age_rating VARCHAR(255) NOT NULL,
    CONSTRAINT fk_concert_venue
        FOREIGN KEY (venue_id) REFERENCES venue (venue_id)
);

CREATE TABLE IF NOT EXISTS concert_price (
    concert_price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id INTEGER NOT NULL,
    rating VARCHAR(30) NOT NULL,
    price INTEGER NOT NULL,
    CONSTRAINT fk_concert_price_concert
        FOREIGN KEY (concert_id) REFERENCES concert (concert_id)
);

CREATE TABLE IF NOT EXISTS concert_schedule (
    concert_schedule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id INTEGER NOT NULL,
    date DATE NOT NULL,
    show_list JSON NOT NULL,
    CONSTRAINT fk_concert_schedule_concert
        FOREIGN KEY (concert_id) REFERENCES concert (concert_id)
);

CREATE TABLE IF NOT EXISTS event (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id INTEGER NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at DATE,
    CONSTRAINT fk_event_concert
        FOREIGN KEY (concert_id) REFERENCES concert (concert_id)
);
