CREATE TABLE IF NOT EXISTS users (
    users_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS venue (
    venue_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS concert (
    concert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id INTEGER NOT NULL,
    img_url VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    booking_cnt INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    running_time INTEGER,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    age_rating VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    show_list JSON NOT NULL,
    CONSTRAINT fk_concert_venue
        FOREIGN KEY (venue_id) REFERENCES venue (venue_id)
);

CREATE TABLE IF NOT EXISTS event (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id INTEGER NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    CONSTRAINT fk_event_concert
        FOREIGN KEY (concert_id) REFERENCES concert (concert_id)
);
